language: php
sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - composer install --ignore-platform-reqs --dev --prefer-dist --no-interaction

script:
  - bin/phing run-tests
  - bin/phing phpmd
