services:

  kgzocha.searcher_bundle.parameter_generator:
    class: KGzocha\Searcher\ParameterGenerator\ParameterGenerator

  kgzocha.searcher_bundle.searcher_factory:
    class: KGzocha\Bundle\SearcherBundle\Searcher\Factory\SearcherFactory
