# In all configuration nodes class will be taken into consideration
# only if there won't be any service specified.
# Service is more important than class.
# If both of them will be specified only service will be used.

k_gzocha_searcher:
  contexts:
    people:
      # optional
      criteria_collection:
        class: KGzocha\Searcher\Criteria\Collection\NamedCriteriaCollection
        service: criteria_collection_service

      # optional
      builder_collection:
        class: KGzocha\Searcher\CriteriaBuilder\Collection\CriteriaBuilderCollection
        service: criteria_builder_collection_service

      # optional
      searcher:
        wrapper_class: KGzocha\Searcher\WrappedResultsSearcher
        class: KGzocha\Searcher\Searcher
        service: searcher_service

      context:
        class: SearchingContextClass
        service: context_service

      criteria:
        - { class: \AgeRangeCriteria, name: ageRange1, service: abc1 }
        - { class: \AgeRangeCriteria, name: ageRange2, service: abc2 }
        - { class: \AgeRangeCriteria, name: ageRange3, service: abc3 }

      builders:
        - { class: \AgeRangeCriteriaBuilder, name: ageRange1, service: def1 }
        - { class: \AgeRangeCriteriaBuilder, name: ageRange1, service: def2 }
        - { class: \AgeRangeCriteriaBuilder, name: ageRange1, service: def3 }

  # optional
  chains:
    people_log:

      # optional
      cell_collection:
        class: \KGzocha\Searcher\Chain\Collection\CellCollection
        service: cell_collection_service

      # optional
      chain_searcher:
        class: \KGzocha\Searcher\Chain\ChainSearch
        service: chain_searcher_service

      transformers:
        - { name: peopleIdToLogId, service: transfomer_service, class: \TransformerClass }

      # at least two are required
      cells:
        - name: peopleCell
          searcher: people
          transformer: peopleIdToLogId
          class: \KGzocha\Searcher\Chain\Cell   # optional
          service: cell_service_1               # optional

        - name: logCell
          searcher: logs
          transformer: ~                        # EndTransformer will be used
          class: \KGzocha\Searcher\Chain\Cell   # optional
          service: cell_service_2               # optional
